name: AliyunpanSDK Release

on:
  workflow_dispatch:
    version:
        description: 'release version'
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    runs-on: macOS-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: release
        run: bundle exec fastlane release $VERSION
        env:
          VERSION: ${{ inputs.version }}
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      
